### ISSUE TITLE
How were you able to collect the hidden A.P.I. fields?

### ISSUE THREAD

**Issue by Windows81** [ShownApe/api#1]
These are very useful for the `sethiddenproperty` and `gethiddenproperty` methods most script executors use.

**Comment by ShownApe** [comment]
some executors such as scriptware and synapse include a gethiddenproperties function that returns a table with the instance’s hidden properties. then i created a bunch of classes and ran gethiddenproperties on each of the games descendants (if the descendant’s class hadn’t been checked already). put all these properties into a table, and formatted it into a string and called setclipboard.

**Comment by Windows81** [comment]
Would you be able to update the hidden fields by the way?  My executor doesn't have `gethiddenproperties` available.
